name: hizmet_mobil_uygulama
description: Hizmet Mobil Uygulama

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^0.5.1
  firebase_auth: ^0.18.2
  cloud_firestore: ^0.14.2
  google_fonts: ^1.1.1
  platform_date_picker: ^0.0.4+1
  shared_preferences: ^0.5.12+4
  flutter_star_rating: ^0.0.3
  get_it: ^5.0.3
  provider: ^4.3.2+3
  google_sign_in: ^4.5.6
  image_picker: ^0.6.7+15
  firebase_storage: ^5.2.0
  fancy_bottom_navigation: ^0.3.2
  line_awesome_flutter: ^1.0.1
  convex_bottom_bar: ^2.6.0
  date_format: ^1.0.9

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true


  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/iller/iller.json
     - assets/carouselPhotos/photo1.jpg
     - assets/carouselPhotos/photo2.jpg
     - assets/carouselPhotos/photo3.jpg
     - assets/Category.json
     - assets/Category/Cat1.png
     - assets/Category/Cat2.png
     - assets/Category/Cat3.png
     - assets/Category/Cat4.png
     - assets/Category/Cat5.png
     - assets/Category/Cat6.png
     - assets/Category/Cat11.png
     - assets/Category/Cat12.png
     - assets/Category/Cat13.png
     - assets/Category/Cat14.png
     - assets/Category/Cat21.png
     - assets/Category/Cat31.png
     - assets/Category/Cat32.png
     - assets/Category/Cat41.png
     - assets/Category/Cat51.png
     - assets/Category/Cat52.png
     - assets/Category/Cat61.png
     - assets/Category/Cat62.png
     - assets/Category/Cat111.png
     - assets/Category/Cat112.png
     - assets/Category/Cat113.png
     - assets/Category/Cat114.png
     - assets/Category/Cat121.png
     - assets/Category/Cat122.png
     - assets/Category/Cat123.png
     - assets/Category/Cat124.png
     - assets/Category/Cat125.png



  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
